name: Static analysis
on: [ pull_request ]
permissions:
  contents: read

jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true
          python-version: "3.13"

      - name: Install the project dependencies
        run: uv sync --frozen

      - name: black
        run: uv run black . --check

  iSort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true
          python-version: "3.13"

      - name: Install the project dependencies
        run: uv sync --frozen

      - name: isort
        run: uv run isort . --check

  MyPy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true
          python-version: "3.13"

      - name: Install the project dependencies
        run: uv sync --frozen

      - name: mypy
        run: uv run mypy --strict .